development:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org_id") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "key") %>

test:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "id") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "key") %>

production:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org_id") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "key") %>
