development:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "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") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org-EOGrquP1yPFFaw49fSAcm91y") %>
test:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "id") %>

production:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "id") %>