development:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "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") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org-EOGrquP1yPFFaw49fSAcm91y") %>
  aws:
    access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID", "key") %>
    secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", "key") %>
test:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "id") %>
  aws:
    access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID", "key") %>
    secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", "key") %>

production:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "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") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org-EOGrquP1yPFFaw49fSAcm91y") %>
  aws:
    access_key_id: <%= ENV.fetch("AWS_ACCESS_KEY_ID", "key") %>
    secret_access_key: <%= ENV.fetch("AWS_SECRET_ACCESS_KEY", "key") %>