development:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "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") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org-EOGrquP1yPFFaw49fSAcm91y") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "0354bdea9c20341b5f1abafcfbc5a108") %>

test:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "id") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "key") %>

production:
  openai:
    access_token: <%= ENV.fetch("OPENAI_ACCESS_TOKEN", "token") %>
    organization_id: <%= ENV.fetch("OPENAI_ORGANIZATION_ID", "org_id") %>
  elevenlabs:
    api_key: <%= ENV.fetch("ELEVENLABS_API_KEY", "key") %>
